[package]
name = "depploy"
version = "0.1.0"
edition = "2018"
author = "Michael Lichtenecker"
homepage = "https://github.com/MichaelProjects/depploy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
shiplift = "0.7"
toml = "0.5.8"
serde = "1.0"
