name: depploy_pipeline

jobs:
  testing:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v1
        with: 
            sharedKey: ${{ matrix.os }}
      - name: run tests
        run: cargo test --release

      - name: run clippy
        run: cargo clippy --release

  build:
    needs: testing
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v1
        with: 
          sharedKey: ${{ matrix.os }}
      - uses: actions/cache@v3
        with:
          path: archive
          key: build_cache
      - name: build depploy
        run: cargo build --release --bin depploy
      - name: zip
        run: |
          echo $RUNNER_OS
          mkdir -p archive
          if [ $RUNNER_OS = "Linux" ]; then
            cd target/release && tar -zcvf ../../archive/depploy.linux-amd64.tar.gz  depploy && cd .. && cd ..
          else
            cd target/release && tar -zcvf ../../archive/depploy.darwin-amd64.tar.gz depploy && cd .. && cd ..
          fi

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: version
        run: echo "::set-output name=version::$(./target/release/depploy --version)"
        id: version
      - uses: actions/cache@v3
        with:
          key: build_cache
          path: archive
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            archive/depploy.darwin-amd64.tar.gz
            archive/depploy.linux-amd64.tar.gz
