name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - uses: actions/cache@v3
        with:
          path: target
          key: build_cache
      - name: install targets
        run: rustup target add x86_64-apple-darwin && rustup target add x86_64-unknown-linux-gnu
      
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --release
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-apple-darwin --release
      
      - name: compress linux
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            target/x86_64-unknown-linux-gnu/release/depploy
          outPath: x86_64-unknown-linux-gnu.tar.gz
      - name: compress macos
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            target/x86_64-apple-darwin/release/depploy
          outPath: x86_64-apple-darwin.tar.gz

      - name: version
        run: echo "::set-output name=version::$(./target/release/depploy --version)"
        id: version

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     prerelease: false
      #     files: |
      #       archive/depploy.darwin-amd64.tar.gz
      #       archive/x86_64-unknown-linux-gnu
      